#!/bin/bash
docker build . -t httpd2.2

#stop any running apache server container
STOP_CONTAINER_ID=`docker ps -aqf "name=wintest11g"`
if [ ! -z $STOP_CONTAINER_ID ]
  then
    docker stop $STOP_CONTAINER_ID
    docker rm $STOP_CONTAINER_ID
fi

# start the new container
CONTAINER_ID=$(docker run --name wintest11g -p 80:80 -p 443:443 -d httpd2.2)
echo apache server container started with id:  $CONTAINER_ID

# tail the logs
docker logs -f $CONTAINER_ID

echo done!!
